### ISSUE TITLE
TypeError: '<' not supported between instances of 'int' and 'datetime.datetime'

### ISSUE THREAD

**Issue by MaximusPrimus** [Sundar0989/WOE-and-IV#1]
`

[test_zs.zip](https://github.com/Sundar0989/WOE-and-IV/files/1998341/test_zs.zip)

`

**Comment by Sundar0989** [comment]
@MaximusPrimus  Can you upload a few data points in a excel here?

**Comment by Sundar0989** [comment]
Please reopen the issue once you have uploaded a few data points. I would be happy to help 👍
