### ISSUE TITLE
data_vars function

### ISSUE THREAD

**Issue by brie93** [Sundar0989/WOE-and-IV#2]
Hi Sundar,

I am new to Python and found this code to be extremely helpful.  Could you explain what this section of the code is doing in the data_vars function?

>     stack = traceback.extract_stack()
>     filename, lineno, function_name, code = stack[-2]
>     vars_name = re.compile(r'\((.*?)\).*$').search(code).groups()[0]
>     final = (re.findall(r"[\w']+", vars_name))[-1]

The reason why I ask is because I got an error in the vars_name line and I'm not sure what is happening here:
> TypeError: expected string or buffer

From some quick StackOverflow searches, I believe this means it is expecting a string from "code", but it is being fed some other data type, perhaps a list.  I quickly added a line to print the type of code and then the python script started working flawlessly.
>     stack = traceback.extract_stack()
>     filename, lineno, function_name, code = stack[-2]
>     print(type(code))
>     vars_name = re.compile(r'\((.*?)\).*$').search(code).groups()[0]
>     final = (re.findall(r"[\w']+", vars_name))[-1]

I'm a bit confused as to what happened, and why adding print(type(code)) would fix the issue.  Could you provide some insight?

Thanks!
Brian

**Comment by Sundar0989** [comment]
Hi Brian,

The data_vars function is invoked using the code below. The code that you have highlighted is written to extract the value "target". So the value of final would be the string "target".

final_iv, IV = data_vars(df,df._**target**_)

final = **"target"**

In python, when you pass a variable to a function, it takes the value of the variable. In this script, we are trying to get the name of the variable being passed to the function and not the value. 

I am surprised to see that a print would fix the issue. If you are okay with sharing your data and the code, I could take a look into what has happened. If not, I please try to run it one more time by restarting the Ipython notebook session. 

Hope that helps. Please let me know if you need any more details. Thanks.

Regards,
Sundar
